### ISSUE TITLE
Plugin doesn't work

### ISSUE THREAD

**Issue by grompere** [TaoK/poor-mans-t-sql-formatter-atom-package#4]
Hi,

I'd like to flag an issue with this plugin. I just installed it on Atom 1.23.1x64 and tried to use it both via the keyboard shortcut (ctrl-k shift-f) and the menu bar button but nothing happened to my SQL file.

I've been a long time user of the poor man's tsql formatter on Notepad++ and made the switch to Atom a couple months ago. I'd really love to use this plugin on Atom so let me know if you need more diagnostic info to help identify the problem.

Zsolt

**Comment by TaoK** [comment]
Once agin, my apologies here - it should be working now, only a year later :(
